spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hanwha?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ubaba
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # ??? (??? ?? ??)
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  server:
    port: 8080
